### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by cmvanb** [zig-gamedev/zig-gamedev#166]
Hi there,

I came across your repo by chance. I love the idea of using zig for games!

Unfortunately `zig build` fails for me with the following error:

```
./build.zig:149:60: error: expected type 'std.mem.Allocator', found 'std.zig.CrossTarget'
    const target = (std.zig.system.NativeTargetInfo.detect(cross) catch unreachable).target;
                                                           ^
/usr/lib/zig/std/mem/Allocator.zig:1:1: note: std.mem.Allocator declared here
//! The standard memory allocation interface.
^
/usr/lib/zig/std/zig/CrossTarget.zig:1:1: note: std.zig.CrossTarget declared here
//! Contains all the same data as `Target`, additionally introducing the concept of "the native target".
^
```

Is there a specific zig version I should be using? Or a dependency I may be missing?

I'm on Arch Linux with a wayland compositor.

**Comment by michal-z** [comment]
Hi, thanks for the report. Project strictly follows latest changes in the Zig compiler so you will need to download latest master build from: https://ziglang.org/download/

**Comment by michal-z** [comment]
One more thing - we don't currently support Wayland, only X11, sorry!

**Comment by cmvanb** [comment]
Ahhhh busted. Oh well, thanks for the reply. Best of luck with the project, looks cool!

**Comment by marler8997** [comment]
Just FYI, most X applications still work with Wayland compositors by going through Wayland.

**Comment by michal-z** [comment]
Thanks for the info I didn't know about it. @cmvanb Could you try it out?

**Comment by cmvanb** [comment]
I installed the latest version of zig.

```
zig version
0.11.0-dev.610+e7d28344f
```

Although `zig build` now completes, when I try to run any of the executables in `/zigout/bin` I get the following:

```
./triangle_wgpu
thread 248902 panic: reached unreachable code
libs/zglfw/src/zglfw.zig:45:5: 0xca6a88 in getRequiredInstanceExtensions (triangle_wgpu)
libs/zgpu/src/zgpu.zig:64:60: 0xc9e979 in impl (triangle_wgpu)
libs/zgpu/src/zgpu.zig:69:32: 0xc9db1f in create (triangle_wgpu)
samples/triangle_wgpu/src/triangle_wgpu.zig:57:49: 0xca010f in init (triangle_wgpu)
samples/triangle_wgpu/src/triangle_wgpu.zig:337:20: 0xca27b4 in main (triangle_wgpu)
/usr/lib/zig/std/start.zig:614:37: 0xca4bb9 in main (triangle_wgpu)
            const result = root.main() catch |err| {
```

**Comment by michal-z** [comment]
Thanks, do you have Vulkan driver installed?

It looks like `VK_KHR_surface` Vulkan extension can't be found on your system (this extension is required to create window surface for rendering).

**Comment by michal-z** [comment]
I've updated the code and now you should get an error message about this issue.

**Comment by cmvanb** [comment]
I'm on the open source `mesa` drivers... doesn't support vulkan.

I had lots of trouble with the official nvidia driver previously. I'll need to find some time to work on it- will report back then.

**Comment by michal-z** [comment]
@cmvanb Did you have a chance to test it with the VK driver?

**Comment by cmvanb** [comment]
@michal-z I've not had a chance, no. I have an idea for a zig game dev project, but other things are taking my time right now.

**Comment by mochalins** [comment]
Just chiming in to say that `zig build` and `zgui`-dependent apps are currently running on my Wayland system (Fedora 39), even with a modern Nvidia graphics card! @marler8997 's comment is spot on, although maybe supporting Wayland directly could be of interest once relevant dependencies have transitioned.

**Comment by hazeycode** [comment]
> Just chiming in to say that `zig build` and `zgui`-dependent apps are currently running on my Wayland system (Fedora 39), even with a modern Nvidia graphics card! @marler8997 's comment is spot on, although maybe supporting Wayland directly could be of interest once relevant dependencies have transitioned.

Thanks for verifying this @mochalins, I'm assuming you meant to type `zgpu` instead of `zgui` there?

Indeed XWayland is taking care of zglfw on Wayland for us at the moment. Note that SDL2 uses Wayland by default and GLFW supports it if compiled with `GLFW_BUILD_WAYLAND`, but we don't do this currently.

I think we should have zglfw compile GLFW with X11 and Wayland support by default. Build options can be added to disable either one of them. We'll also want to vendor the necessary system libraries in system-sdk. I will leave this issue open for addressing this.

**Comment by mochalins** [comment]
> > Just chiming in to say that `zig build` and `zgui`-dependent apps are currently running on my Wayland system (Fedora 39), even with a modern Nvidia graphics card! @marler8997 's comment is spot on, although maybe supporting Wayland directly could be of interest once relevant dependencies have transitioned.
> 
> 
> 
> Thanks for verifying this @mochalins, I'm assuming you meant to type `zgpu` instead of `zgui` there?
> 
> 
> 
> Indeed XWayland is taking care of zglfw on Wayland for us at the moment. Note that SDL2 uses Wayland by default and GLFW supports it if compiled with `GLFW_BUILD_WAYLAND`, but we don't do this currently.
> 
> 
> 
> I think we should have zglfw compile GLFW with X11 and Wayland support by default. Build options can be added to disable either one of them. We'll also want to vendor the necessary system libraries in system-sdk. I will leave this issue open for addressing this.

I did in fact mean zgui, although I should've specified the using the zglfw/zgpu backend. Vendoring dependencies to include Wayland support in the GLFW build sounds reasonable; I'll start work on it and PR if it's not already underway on your end @hazeycode

**Comment by hazeycode** [comment]
I probably won't get round to it for a while. A PR would be very welcome. Thanks!

**Comment by hazeycode** [comment]
@mochalins did you manage to make any progress compiling glfw with native wayland support?

**Comment by mochalins** [comment]
@hazeycode Apologies, I did have some work done but had to shift focus due to rapidly changing work priorities. It is not in an organized enough state to draft PR, and I don't foresee having the availability to clean it up and post within the next few weeks.

**Comment by hazeycode** [comment]
No problem. We will pick this up. Thanks
