### ISSUE TITLE
Dynamic linking all the zig-gamedev dependencies in a project

### ISSUE THREAD

**Issue by tanis2000** [zig-gamedev/zig-gamedev#245]
Hi @michal-z I have been fiddling around with zig-gamedev and so far it really feels awesome! 

I have one project where I am pulling in all the zig-gamedev libraries and including them in my build. It works fine but every time I change a single line of code in my project's code, it takes about 7 seconds to build it again (I am on an MBP M2 Max).

Is there any way to have the dependencies compiled as dynamic libraries during development and link them up instead of recompiling them all the time? Or do you feel I have something broken in my build as I guess that zig should keep everything in cache and only recompile what is really needed.

It would be great if you could help with this. Cheers!

**Comment by michal-z** [comment]
Hi! 

It does not sound right, is your project open-source? I would like to see your `build.zig` if possible.

Thanks,
Michal

**Comment by tanis2000** [comment]
I haven't yet published anything as I want to get to some point where it makes sense to open it for others. 
Here is the build.zig:

```zig
const std = @import("std");
const zgpu = @import("libs/zig-gamedev/libs/zgpu/build.zig");
const zmath = @import("libs/zig-gamedev/libs/zmath/build.zig");
const zpool = @import("libs/zig-gamedev/libs/zpool/build.zig");
const zglfw = @import("libs/zig-gamedev/libs/zglfw/build.zig");
const zstbi = @import("libs/zig-gamedev/libs/zstbi/build.zig");
const zgui = @import("libs/zig-gamedev/libs/zgui/build.zig");
const zflecs = @import("libs/zig-gamedev/libs/zflecs/build.zig");

const assets_dir = "assets/";

const ProcessAssetsStep = @import("src/utils/process_assets.zig").ProcessAssetsStep;

// Although this function looks imperative, note that its job is to
// declaratively construct a build graph that will be executed by an external
// runner.
pub fn build(b: *std.Build) void {
    // Standard target options allows the person running `zig build` to choose
    // what target to build for. Here we do not override the defaults, which
    // means any target is allowed, and the default is native. Other options
    // for restricting supported target set are available.
    const target = b.standardTargetOptions(.{});

    // Standard optimization options allow the person running `zig build` to select
    // between Debug, ReleaseSafe, ReleaseFast, and ReleaseSmall. Here we do not
    // set a preferred release mode, allowing the user to decide how to optimize.
    const optimize = b.standardOptimizeOption(.{});

    const exe = b.addExecutable(.{
        .name = "zig-adventure",
        // In this case the main source file is merely a path, however, in more
        // complicated build scripts, this could be a generated file.
        .root_source_file = .{ .path = "src/main.zig" },
        .target = target,
        .optimize = optimize,
    });

    // This declares intent for the executable to be installed into the
    // standard location when the user invokes the "install" step (the default
    // step when running `zig build`).
    exe.install();

    // This *creates* a RunStep in the build graph, to be executed when another
    // step is evaluated that depends on it. The next line below will establish
    // such a dependency.
    const run_cmd = exe.run();

    // By making the run step depend on the install step, it will be run from the
    // installation directory rather than directly from within the cache directory.
    // This is not necessary, however, if the application depends on other installed
    // files, this ensures they will be present and in the expected location.
    run_cmd.step.dependOn(b.getInstallStep());

    // This allows the user to pass arguments to the application in the build
    // command itself, like this: `zig build run -- arg1 arg2 etc`
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    // This creates a build step. It will be visible in the `zig build --help` menu,
    // and can be selected like this: `zig build run`
    // This will evaluate the `run` step rather than the default, which is "install".
    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);

    const zglfw_pkg = zglfw.Package.build(b, target, optimize, .{});
    exe.addModule("zglfw", zglfw_pkg.zglfw);
    zglfw_pkg.link(exe);

    const zflecs_pkg = zflecs.Package.build(b, target, optimize, .{});
    exe.addModule("zflecs", zflecs_pkg.zflecs);
    zflecs_pkg.link(exe);

    const zpool_pkg = zpool.Package.build(b, .{});
    const zgpu_pkg = zgpu.Package.build(b, .{
        .deps = .{ .zpool = zpool_pkg.zpool, .zglfw = zglfw_pkg.zglfw },
    });
    exe.addModule("zgpu", zgpu_pkg.zgpu);
    zgpu_pkg.link(exe);

    const zstbi_pkg = zstbi.Package.build(b, target, optimize, .{});
    exe.addModule("zstbi", zstbi_pkg.zstbi);
    zstbi_pkg.link(exe);

    const zmath_pkg = zmath.Package.build(b, .{});
    exe.addModule("zmath", zmath_pkg.zmath);

    const assets = ProcessAssetsStep.init(b,
    "assets",
    "src/assets.zig",
    "src/animations.zig",
    &.{"images"});
    const process_assets_step = b.step("process-assets", "generates struct for all assets");
    process_assets_step.dependOn(&assets.step);

    const install_assets_step = b.addInstallDirectory(.{
        .source_dir = thisDir() ++ "/" ++ assets_dir,
        .install_dir = .{ .custom = "" },
        .install_subdir = "bin/" ++ assets_dir,
    });
    exe.step.dependOn(&install_assets_step.step);



    // Creates a step for unit testing.
    const exe_tests = b.addTest(.{
        .root_source_file = .{ .path = "src/main.zig" },
        .target = target,
        .optimize = optimize,
    });

    // Similar to creating the run step earlier, this exposes a `test` step to
    // the `zig build --help` menu, providing a way for the user to request
    // running the unit tests.
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&exe_tests.step);
}

inline fn thisDir() []const u8 {
    return comptime std.fs.path.dirname(@src().file) orelse ".";
}
```

**Comment by michal-z** [comment]
Looks fine. Normally Zig compiler should cache build artifacts and not re-compile the libs every time. I don't have macOS machine here to test it unfortunately.

What happens when you modify a single sample app in the zig-gamedev and then `zig build`?

@kamidev Do you observe similar issue on macOS?

**Comment by tanis2000** [comment]
I've just tried that with one of the samples and yes, the behavior is exactly the same.

```sh
time zig build
zig build  7,71s user 5,71s system 188% cpu 7,140 total
```

**Comment by michal-z** [comment]
Not sure how I can help here..
There are some upcoming changes to the compiler which should help. Please see here for example: https://github.com/ziglang/zig/pull/14647

**Comment by tanis2000** [comment]
Yes I believe it might be an issue with parallelism (or actually no parallelism) during the build steps. Thanks for the effort anyway! 😉

**Comment by kamidev** [comment]
> Looks fine. Normally Zig compiler should cache build artifacts and not re-compile the libs every time. I don't have macOS machine here to test it unfortunately.
> 
> What happens when you modify a single sample app in the zig-gamedev and then `zig build`?
> 
> @kamidev Do you observe similar issue on macOS?

Yes, I have the same issues on my MBP M1 Max. But as @michal-z says, there are ongoing efforts to improve zig's build process likely to help.

**Comment by tanis2000** [comment]
I have just updated to the latest master, fixed my custom build step as that has also been changed as part of the parallel implementation and the result seems to be the same.

A single change on any line of code leads to the following:

```
time zig build
zig build  7.49s user 1.00s system 128% cpu 6.583 total
```

Not much of a difference. Are you sure parallel compilation is enabled on Apple Silicon? And btw I have the feeling most of that time is spent in the linker.

**Comment by hazeycode** [comment]
Has this improved for you at all @tanis2000?

On main branch using 0.12.0-dev.2063+804cee3b9 on an M3 Pro MBP, here's what I'm getting:

Initial build `zig build  205.17s user 31.44s system 849% cpu 27.868 total`

After changing a single sample `zig build  1.48s user 1.91s system 150% cpu 2.250 total`

**Comment by kamidev** [comment]
Looks good for me too, now.

On M3 Max, with clean cache and empty zig-out
```
➜  zig-gamedev git:(main) time gzig build
/Users/jonas/src/zig/zig-macos-aarch64-0.12.0-dev.2063+804cee3b9/zig build  
152.50s user 43.73s system 1166% cpu 16.820 total
```

After trivial change to one sample.

```
➜  zig-gamedev git:(main) time gzig build
/Users/jonas/src/zig/zig-macos-aarch64-0.12.0-dev.2063+804cee3b9/zig build  
0.37s user 2.13s system 239% cpu 1.044 total
```

**Comment by tanis2000** [comment]
Same kind of Mac on my end, an M3 Max. Similar results.

Compiling from scratch:

```
zig-gamedev git:(main) time zig build
zig build  154,43s user 63,90s system 1175% cpu 18,574 total
➜  zig-gamedev git:(main)
```

After a small change in one of the samples:

```
zig-gamedev git:(main) ✗ time zig build
zig build  1,49s user 4,74s system 356% cpu 1,746 total
➜  zig-gamedev git:(main) ✗
```

It still looks like a lot of time compared to my usual C codebase but I am pretty sure that now it's not because of some settings in this project but rather the zig compiler itself.

The next challenge would be to reduce the zig-cache and zig-out size

```
900M	zig-cache
499M	zig-out
```

I wonder if using `wgpu-native` would make any difference as you would not have to bring in all the weight of dawn.

**Comment by hazeycode** [comment]
> I wonder if using `wgpu-native` would make any difference as you would not have to bring in all the weight of dawn.

It would be cool to compare a wgpu-native zgpu backend with dawn in terms of size, performance, stability, etc. But it's quite a lot of work that could lead to nowhere.

**Comment by tanis2000** [comment]
@hazeycode IIRC Mike is working on something similar. He is using the wgpu-native stuff from within zig in one of his project. Not entirely sure how far he got with that, though: https://github.com/prime31/zig-aya/tree/new-wgpu-native-base
