### ISSUE TITLE
zflecs: Dependency loop compile error

### ISSUE THREAD

**Issue by foxnne** [zig-gamedev/zig-gamedev#282]
```ts src/deps/zig-gamedev/zflecs/src/zflecs.zig:73:5: error: dependency loop detected
pub const iter_action_t = *const fn (it: *iter_t) callconv(.C) void;
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    iter_t: src/deps/zig-gamedev/zflecs/src/zflecs.zig:472:27
    iter_next_action_t: src/deps/zig-gamedev/zflecs/src/zflecs.zig:82:48
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

Zig 0.11.0-dev.2571+31738de28

**Comment by michal-z** [comment]
Could you try the latest code?

**Comment by foxnne** [comment]
That workaround gets me back working again, thanks!

**Comment by hazeycode** [comment]
This seems to be fixed now (using Zig 0.12.0-dev.1871+e426ae43a). Can you confirm that it's working for you without the workaround?

**Comment by foxnne** [comment]
> This seems to be fixed now (using Zig 0.12.0-dev.1871+e426ae43a). Can you confirm that it's working for you without the workaround?

I'm a bit blocked by mach at the moment to update to that version, but as soon as I can test I will confirm. Thanks!

**Comment by hazeycode** [comment]
I didn't read the Zig version you posted properly and assumed the bug was fixed as with https://github.com/zig-gamedev/zig-gamedev/issues/371. This is still a bug. Upstream issue: https://github.com/zig-gamedev/zig-gamedev/issues/371

**Comment by hazeycode** [comment]
Fixed by https://github.com/Pyrolistical/zig-gamedev/commit/1e5d52abad485fbfb76b65ca3394796e79a1ec6f
