### ISSUE TITLE
[ztracy] not working with release builds on windows?

### ISSUE THREAD

**Issue by Avokadoen** [zig-gamedev/zig-gamedev#334]
I'm honestly unsure if this is me using ztracy wrong, or if there is something wrong with ztracy. After zig got the self-hosted compiler I have failed to build my library [ecez](https://github.com/Avokadoen/ecez) with ztracy enabled in release builds on windows. Is this something that has been observed before?

Both ReleaseSafe and ReleaseFast
```txt
$ zig build run-game-of-life -Denable-tracy=true -Doptimize=ReleaseFast
run game-of-life: error: the following command exited with error code 5:
C:\repositories\ecez\zig-out\bin\game-of-life.exe
Build Summary: 6/8 steps succeeded; 1 failed (disable with --summary none)
run-game-of-life transitive failure
+- run game-of-life failure
error: the following build command failed with exit code 1:
C:\repositories\ecez\zig-cache\o\f0ed3b39f36562475f11febfd69e057c\build.exe C:\Program Files\Zig\zig.exe C:\repositories\ecez C:\repositories\ecez\zig-cache C:\Users\avokado\AppData\Local\zig run-game-of-life -Denable-tracy=true -Doptimize=ReleaseFast
```

Debug works:
```txt
$ zig build run-game-of-life -Denable-tracy=true -Doptimize=Debug
[ ][ ][ ][X][ ][ ][ ][ ][X][X][X][ ][X][X][X][X][ ][ ][X][ ][ ][X][ ][ ][ ][X][ ][X][ ][ ]
...
```

ecez issue: https://github.com/Avokadoen/ecez/issues/67

**Comment by michal-z** [comment]
Thanks for the report, I will check it on my side.

**Comment by Avokadoen** [comment]
I tried digging in the zig repo to find any filed bugs that might be related:

- https://github.com/ziglang/zig/issues/11035
- https://github.com/ziglang/zig/issues/576
- https://github.com/ziglang/zig/issues/14341

**Comment by Avokadoen** [comment]
Seems like tracy compiles with latest zig, but I am having a issue where all zone get the same name, color and src.

**Comment by Avokadoen** [comment]
example:
![image](https://github.com/zig-gamedev/zig-gamedev/assets/26302304/8c438655-3939-4a3d-b427-229a646baf40)

**Comment by hazeycode** [comment]
Also reported here https://github.com/zig-gamedev/zig-gamedev/pull/530#issuecomment-2020224643

**Comment by Avokadoen** [comment]
Ok, good to know that you are aware about it! 
I am closing this issue since it is not present on newer versions of zig
