### ISSUE TITLE
Compiling Jolt from source gives a compilation error, but I'm posting here the solution

### ISSUE THREAD

**Issue by bovacu** [zig-gamedev/zig-gamedev#439]
When compiling the whole lib from source and also compiling your C API, I encountered a compilation error:

```
In file included from JoltPhysicsC_Extensions.cpp:12:
In file included from ../Jolt/Jolt.h:8:
In file included from ../Jolt/Core/Core.h:263:
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/sstream:447:14: error: '__xfer_bufptrs' redeclared with 'public' access
      struct __xfer_bufptrs
             ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/sstream:74:14: note: previously declared 'private' here
      struct __xfer_bufptrs;
             ^
1 error generated.
```
This error is generated due to this line of code in JoltC/JoltPhysicsC_Extensions.cpp:
`#define private public`

The error is solved by modifying the source code of Jolt just a bit, on file Jolt/Core/Core.h we have the include of std headers:
```
// Standard C++ includes
JPH_SUPPRESS_WARNINGS_STD_BEGIN
#include <vector>
#include <utility>
#include <cmath>
#include <sstream>
#include <functional>
#include <algorithm>
JPH_SUPPRESS_WARNINGS_STD_END
#include <limits.h>
#include <float.h>
#include <string.h>
#if defined(JPH_USE_SSE)
	#include <immintrin.h>
#elif defined(JPH_USE_NEON)
	#ifdef JPH_COMPILER_MSVC
		#include <intrin.h>
		#include <arm64_neon.h>
	#else
		#include <arm_neon.h>
	#endif
#endif
```
It is needed to add those lines:
```
#undef private
#define private private
// Standard C++ includes
JPH_SUPPRESS_WARNINGS_STD_BEGIN
#include <vector>
#include <utility>
#include <cmath>
#include <sstream>
#include <functional>
#include <algorithm>
JPH_SUPPRESS_WARNINGS_STD_END
#include <limits.h>
#include <float.h>
#include <string.h>
#if defined(JPH_USE_SSE)
	#include <immintrin.h>
#elif defined(JPH_USE_NEON)
	#ifdef JPH_COMPILER_MSVC
		#include <intrin.h>
		#include <arm64_neon.h>
	#else
		#include <arm_neon.h>
	#endif
#endif
#undef private
#define private public
```

And there you go, it compiles perfectly now. I could not make a PR as I tried to public my branch with the change and I had no permissions, so this is the solution in case you want to apply it.

I encountered this problem because I want to use this Jolt library in my C engine, and the Jolt repo points to your repo. 

This fix will be overwritten in case a new version of Jolt/Core/Core.h is pulled from the official repo.

**Comment by michal-z** [comment]
Thanks for the info. Note that we compile JoltC using `zig cc` (`clang`) and it works fine. What compiler do you use?

**Comment by bovacu** [comment]
I compiled it with clang++, which seems strange to fail then. I compiled it with clang++ on windows, linux and mac and got the same error on the 3 platforms, this fix solved the problem for all platforms. Maybe it is a problem on how I compiled it but I don't know, I just compiled all of the source files to generate a lib and this fix was needed. Well, this thread can still be of help to anyone trying to compile it like me if they encounter this problem!

**Comment by hazeycode** [comment]
This is probably due to the access control hack in JoltPhysicsC_Extensions.cpp

I think the fix might be to delete this hack and instead add `-fno-access-control` to our compile flags in build.zig

This way we can avoid hacking upstream Jolt headers

**Comment by hazeycode** [comment]
@bovacu I've made the this change. Can you confirm if it resolves the issue for you? https://github.com/michal-z/zig-gamedev/commit/c20107a32c8117f008f4598219d5d27e3ad39d22

**Comment by bovacu** [comment]
Hey, I tried it and it seems to be working fine!

**Comment by hazeycode** [comment]
Thanks!
