### ISSUE TITLE
[zgpu] Option to specify wgpu required features

### ISSUE THREAD

**Issue by Senryoku** [zig-gamedev/zig-gamedev#465]
Hi,

I needed the `bgra8_unorm_storage` wgpu feature in one of my project but couldn't find a way to request it using zgpu, did I miss something?
I wrote a [very simple patch](https://github.com/Senryoku/zig-gamedev/commit/afafae5b04c969a2bfe7f0dfd48fc5a083ccd112) that fits my needs. Probably not worth a PR, but I can submit it if you want.

Thanks for the libraries!

**Comment by hazeycode** [comment]
Hi, yes please submit a PR. Note that the optional is not needed, defaulting to an empty slice should work fine.
