### ISSUE TITLE
Tests not linking SDL on Windows

### ISSUE THREAD

**Issue by hazeycode** [zig-gamedev/zig-gamedev#467]
Fails here -> https://github.com/zig-gamedev/zig-gamedev/actions/runs/7700805077 with commit https://github.com/zig-gamedev/zig-gamedev/commit/028522e0ebdab0b2290d3dcce5f34a1805808ba6

Undo this commit -> https://github.com/zig-gamedev/zig-gamedev/commit/f0a2b026d86401494fcaa2d74ed73b370491810f

**Comment by Pyrolistical** [comment]
https://github.com/zig-gamedev/zig-gamedev/issues/510 is blocked by this as openvr comes with a `.dll` that needs to linked in the same way as sdl

**Comment by Pyrolistical** [comment]
a workaround is to copy the .dll to where the .exe is

**Comment by Pyrolistical** [comment]
the symptom is exit code 53 if the .dll is not found by the linked .exe

**Comment by Pyrolistical** [comment]
Is this related to https://github.com/ziglang/zig/issues/5289 ?

**Comment by hazeycode** [comment]
> Is this related to [ziglang/zig#5289](https://github.com/ziglang/zig/issues/5289) ?

I'm not sure. But it appears to have been fixed by https://github.com/zig-gamedev/zig-gamedev/pull/518.

However there is a regression on Windows. I tried reapplying your `setCwd` change (https://github.com/Pyrolistical/zig-gamedev/commit/4aa6a7acf5d3bd093ed9d25c1aa929068ece0d89) but it doesn't work now. Sorry, I will try to fix it.
