### ISSUE TITLE
zopengl is missing the DEBUG_OUTPUT capability to enable debugging in 4.3 core profile

### ISSUE THREAD

**Issue by robinheydon** [zig-gamedev/zig-gamedev#489]
The ability to enable debugging of OpenGL was enhanced in 4.3 core profile with the addition of the debugging callbacks. These are in the zopengl bindings. However, the DEBUG_OUTPUT capability value (0x92E0) was not defined, not allowing the glEnable (GL_DEBUG_OUTPUT) to be called.

**Comment by hazeycode** [comment]
FYI the bindings for core 4.1 onwards are largely untested and incomplete so far.

**Comment by robinheydon** [comment]
Yes, I noticed - I'm not needing those bindings yet. If I do, then I'll create a PR for them.

**Comment by hazeycode** [comment]
That's great, thanks!
