### ISSUE TITLE
[zmath] Does lookToLh need the transpose?

### ISSUE THREAD

**Issue by robinheydon** [zig-gamedev/zig-gamedev#498]
The current code for lookToLh (zmath.zig:2264) function creates a matrix and then transposes it. Yet, we could just generate the transposed matrix directly without having to then call transpose.

Current code:

>     pub fn lookToLh(eyepos: Vec, eyedir: Vec, updir: Vec) Mat {
>         const az = normalize3(eyedir);
>         const ax = normalize3(cross3(updir, az));
>         const ay = normalize3(cross3(az, ax));
>         return transpose(.{
>             f32x4(ax[0], ax[1], ax[2], -dot3(ax, eyepos)[0]),
>             f32x4(ay[0], ay[1], ay[2], -dot3(ay, eyepos)[0]),
>             f32x4(az[0], az[1], az[2], -dot3(az, eyepos)[0]),
>             f32x4(0.0, 0.0, 0.0, 1.0),
>         });
>     }

Less verbose code:

>     pub fn lookToLh(eyepos: Vec, eyedir: Vec, updir: Vec) Mat {                                     
>         const az = normalize3(eyedir);                                                              
>         const ax = normalize3(cross3(updir, az));                                                   
>         const ay = normalize3(cross3(az, ax));                                                      
>         return .{                                                                                   
>             f32x4(ax[0], ay[0], az[0], 0),                                                          
>             f32x4(ax[1], ay[1], az[1], 0),                                                          
>             f32x4(ax[2], ay[2], az[2], 0),                                                          
>             f32x4(-dot3(ax, eyepos)[0], -dot3(ay, eyepos)[0], -dot3(az, eyepos)[0], 1.0),               
>         };                                                                                          
>     }                                                                                               

The output of these are the same as verified by the `zmath.matrix.lookToLh` test.

If you agree with this change, I'm happy to create a pull request for this.

**Comment by hazeycode** [comment]
Yes please create a PR with this change. Thanks!

**Comment by hazeycode** [comment]
Resolved by 28aa650e1f67a93c222d00325d18465561ad33f5. Thanks!
