### ISSUE TITLE
Tracy Zone Name Mismatch

### ISSUE THREAD

**Issue by jcalabro** [zig-gamedev/zig-gamedev#535]
Creating an issue for discussion separate from the PR (#530)

When using latest zig (or the most recent Mach nominated Zig), all of the zones we emit to Tracy take one name (it appears to be the first zone I use):

![image](https://github.com/zig-gamedev/zig-gamedev/assets/8205547/ad93433f-f8f8-4336-9f1c-4817419900bd)

I did some poking around and noticed that if I heap allocate the [___tracy_source_location_data](https://github.com/zig-gamedev/zig-gamedev/blob/078c568d2b37ea613c194641797a1be21ad6fc39/libs/ztracy/src/ztracy.zig#L322-L331) object, it works fine (though heap allocating here is not super awesome). I also noticed that if I just don't use the local `static` struct in [this commit](https://github.com/jcalabro/zig-gamedev/commit/7c23e43ff0bf0b63f58c5b46e257f27a6afe7d52) for example, it also works just fine.

![image](https://github.com/zig-gamedev/zig-gamedev/assets/8205547/ae0f75b3-4895-4126-96b5-6625ec88831c)

I am going to be totally honest, I'm not sure why this is the case. There's also a lot of Zig commits to dig through to try and find out what changed. Any chance you know off the top of your head? Otherwise, I can float it in Discord.

**Comment by hazeycode** [comment]
@jcalabro looks like @robinheydon identified the problem here  https://github.com/zig-gamedev/zig-gamedev/pull/536/commits/6b44e904fabc2269a7dbfcb4ecc842c1176e085f but I haven't verified yet

**Comment by jcalabro** [comment]
Just tried the fix and it works great for me. Thanks all! Will do some reading on those issues in the comments :eyes:

**Comment by hazeycode** [comment]
Nice! Thanks for checking. But let's leave this open until this change is merged.
