### ISSUE TITLE
zgui d3d12 assertion

### ISSUE THREAD

**Issue by hazeycode** [zig-gamedev/zig-gamedev#544]
Hmm, this change broke my local wip with:
```sh
Assertion failed: viewport->RendererUserData == 0 && viewport->PlatformUserData == 0, file ...\libs\zgui\libs\imgui\imgui.cpp, line 15466
```

Its during the reinit of zgui in d3d12. The frame pacing sample reinit works in wgpu, so could be something with the d3d12 backend

_Originally posted by @Pyrolistical in https://github.com/zig-gamedev/zig-gamedev/issues/537#issuecomment-2040591557_

**Comment by Pyrolistical** [comment]
I was able to workaround this issue by just not re-initing zgui. I was being silly and re-initing zgui and zglfw just to switch between windowed mode and fullscreen.

I think I can rework one of the samples to repo this

**Comment by Pyrolistical** [comment]
Ah, here we go. It has something to do with setMontior:
```zig
diff --git a/samples/minimal_zgui_glfw_d3d12/src/minimal_zgui_glfw_d3d12.zig b/samples/minimal_zgui_glfw_d3d12/src/minimal_zgui_glfw_d3d12.zig
index 697fca05..207abd16 100644
--- a/samples/minimal_zgui_glfw_d3d12/src/minimal_zgui_glfw_d3d12.zig
+++ b/samples/minimal_zgui_glfw_d3d12/src/minimal_zgui_glfw_d3d12.zig
@@ -33,6 +33,7 @@ pub fn main() !void {
     const glfw_window = try glfw.Window.create(800, 600, window_name, null);
     defer glfw_window.destroy();
     glfw_window.setSizeLimits(400, 400, -1, -1);
+    glfw_window.setMonitor(null, 0, 0, 800, 600, -1);

     zgui.init(allocator);
     defer zgui.deinit();
```

**Comment by OndraVoves** [comment]
I found this https://github.com/ocornut/imgui/issues/4941

**Comment by hazeycode** [comment]
@Pyrolistical I am able to repro this without adding the `setMonitor` call. Maybe it's a timing issue

**Comment by hazeycode** [comment]
@OndraVoves swapping those calls round fixes it. Thanks

**Comment by Pyrolistical** [comment]
Thank you, confirmed fixed for me.
