### ISSUE TITLE
zd3d12 lib MipmapGenerator depends on sample

### ISSUE THREAD

**Issue by Pyrolistical** [zig-gamedev/zig-gamedev#556]
[`MipmapGenerator`](https://github.com/zig-gamedev/zig-gamedev/blob/828a0786940976833b341deef791dc8303973f53/libs/zd3d12/src/zd3d12.zig#L1784) depends on a compiled compute shader under `content_dir ++ "shaders/generate_mipmaps.cs.cso"`

That file is build time compiled in each sample: https://github.com/zig-gamedev/zig-gamedev/blob/828a0786940976833b341deef791dc8303973f53/samples/simple_raytracer/build.zig#L88-L97

Second, `content_dir` is a sample concept that libs should not have.

Related to this I find it awkward a lib would directly load from the filesystem instead of be given the bytes. By allowing the caller to pass in the bytes, it can decide to either:
  1. load it from the filesystem
  2. [compile it at runtime](https://github.com/zig-gamedev/zig-gamedev/blob/main/libs/zwin32/src/d3dcompiler.zig)
  3. already have loaded via `@embedFile`

**Comment by Pyrolistical** [comment]
Here are all places zd3d12 opens a file:
```
...\zig-gamedev\zig-gamedev\libs\zd3d12\src\zd3d12.zig
  1018,29:             const vs_file = std.fs.openFileAbsolute(abspath, .{}) catch unreachable;
  1028,29:             const gs_file = std.fs.openFileAbsolute(abspath, .{}) catch unreachable;
  1036,29:             const ps_file = std.fs.openFileAbsolute(abspath, .{}) catch unreachable;
  1134,29:             const as_file = std.fs.openFileAbsolute(abspath, .{}) catch unreachable;
  1142,29:             const ms_file = std.fs.openFileAbsolute(abspath, .{}) catch unreachable;
  1152,29:             const ps_file = std.fs.openFileAbsolute(abspath, .{}) catch unreachable;
  1234,29:             const cs_file = std.fs.openFileAbsolute(abspath, .{}) catch unreachable;
```

**Comment by hazeycode** [comment]
> Should we fix this issue making a breaking change to convert all those from file paths to bytes?

Yes. Ideally the user should decide how shaders are supplied, if they aren't simply embedded in the lib.

> We can make the breakage obvious by having the caller provide a [`SHADER_BYTECODE`](https://github.com/zig-gamedev/zig-gamedev/blob/828a0786940976833b341deef791dc8303973f53/libs/zwin32/src/d3d12.zig#L801-L808), so it doesn't just go from `[]u8` path to `[]u8` bytes

Good idea.

**Comment by Pyrolistical** [comment]
OK. I'll get a PR up
