### ISSUE TITLE
[zglfw] Add `glfwShowWindow` functionality to bindings

### ISSUE THREAD

**Issue by terraquad** [zig-gamedev/zig-gamedev#582]
I've been following a tutorial online on how to set up GLFW, and the tutorial uses the `glfwShowWindow` function. I've searched for the function using ZLS (in Vs code) but there aren't any similar functions on `glfw.Window.show()` or `glfw.showWindow()`.

1. Does anyone know if a binding exists? (and if yes, which function is it?)
2. It would be cool if someone added documentation for the exposed functions since I have to look up their meaning on glfw.org every time.

Thanks in advance :)

**Comment by hazeycode** [comment]
Looks like this binding doesn't exist. I guess nobody needed it so far. We should add it.

I'm planning to employ Zig's new autodoc feature to provide all of us with handy API reference.

**Comment by vortexofdoom** [comment]
Is there any more to creating a binding here than just:
```zig
pub fn show(window: *Window) void {
    glfwShowWindow(window);
}
extern fn glfwShowWindow(window: *Window) void;

**Comment by hazeycode** [comment]
Just that is all that's needed for binding simple C APIs.
