### ISSUE TITLE
[zopengl] Wrong name in opengl function glGetInternalformativ

### ISSUE THREAD

**Issue by amarsero** [zig-gamedev/zig-gamedev#590]
Hi,
i am unable to open a context with opengl 4.2 because it can't find the function "glGetInternalFormativ". 
https://github.com/zig-gamedev/zig-gamedev/blob/4c86e7cebfc3b9cd288d70d6e0033e04455862f7/libs/zopengl/src/zopengl.zig#L611
I found that the name is wrong, it should be "glGetInternalformativ", with a lowercase f.
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glGetInternalformat.xhtml

When fixed i can open a context up to opengl 4.6.

If this is ok, i'll open a PR.
Also, should i change the name of the binding?

**Comment by hazeycode** [comment]
Hi, yes please open a PR with the name fixed.

Note that loading procs with 4.6 specified will not load any APIs post-4.2 because these bindings are yet to be implemented. We should probably assert that the API version the user tries to load is valid and supported.

**Comment by hazeycode** [comment]
> Note that loading procs with 4.6 specified will not load any APIs post-4.2 because these bindings are yet to be implemented. We should probably assert that the API version the user tries to load is valid and supported.

What I said here isn't quite correct, some bindings post-4.2 are implemented and loaded but coverage is incomplete. And we already assert that the version is within a valid range (although this could be improved).
