### ISSUE TITLE
ztracy build failed

### ISSUE THREAD

**Issue by Luna1996** [zig-gamedev/zig-gamedev#601]
>zig build test
test
└─ run ztracy-tests
   └─ zig test ztracy-tests Debug native
      └─ zig build-lib tracy Debug native 2 errors
<command line>:12:9: error: '_WIN32_WINNT' macro redefined
<built-in>:496:2: note: in file included from <built-in>:496:
<command line>:9:9: note: previous definition is here
C:\Users\23209\Documents\Repo\repo.zig\zig-gamedev\libs\ztracy\libs\tracy/client/TracyProfiler.cpp:285:5: error: use of undeclared identifier '__cpuidex'
    __cpuidex( (int*)regs, leaf, 0 );
    ^
C:\Users\23209\Documents\Repo\repo.zig\zig-gamedev\libs\ztracy\libs\tracy\TracyClient.cpp:23:10: note: in file included from C:\Users\23209\Documents\Repo\repo.zig\zig-gamedev\libs\ztracy\libs\tracy\TracyClient.cpp:23:
#include "client/TracyProfiler.cpp"
         ^
error: the following command failed with 2 compilation errors:
C:\Users\23209\AppData\Roaming\Code\User\globalStorage\ziglang.vscode-zig\zig_install\zig.exe build-lib -cflags -DTRACY_ENABLE  -D_WIN32_WINNT=0x601 -fno-sanitize=undefined -- C:\Users\23209\Documents\Repo\repo.zig\zig-gamedev\libs\ztracy\libs\tracy\TracyClient.cpp -lws2_32 -ldbghelp -ODebug -I C:\Users\23209\Documents\Repo\repo.zig\zig-gamedev\libs\ztracy\libs\tracy\tracy -Mroot -lc++ -lc --cache-dir C:\Users\23209\Documents\Repo\repo.zig\zig-gamedev\zig-cache --global-cache-dir C:\Users\23209\AppData\Local\zig --name tracy -static --listen=- 
Build Summary: 63/67 steps succeeded; 1 failed; 176/177 tests passed; 1 skipped (disable with --summary none)
test transitive failure
└─ run ztracy-tests transitive failure
   └─ zig test ztracy-tests Debug native transitive failure
      └─ zig build-lib tracy Debug native 2 errors
error: the following build command failed with exit code 1:
C:\Users\23209\Documents\Repo\repo.zig\zig-gamedev\zig-cache\o\cd78262eec12716aff0934830dacbd6d\build.exe C:\Users\23209\AppData\Roaming\Code\User\globalStorage\ziglang.vscode-zig\zig_install\zig.exe C:\Users\23209\Documents\Repo\repo.zig\zig-gamedev C:\Users\23209\Documents\Repo\repo.zig\zig-gamedev\zig-cache C:\Users\23209\AppData\Local\zig --seed 0x619d1193 -Zd50b4aed71314833 test

**Comment by a-day-old-bagel** [comment]
I can also reproduce, and I can solve the issue (for my machine) [by commenting out these lines](https://github.com/zig-gamedev/zig-gamedev/compare/main...a-day-old-bagel:zig-gamedev:temp2)

Obviously this probably isn't the actual solution, since it will probably break someone else's build depending on their environment. I'm just providing this as a hint about where the problem is coming from.

**Comment by hazeycode** [comment]
I think the fix for the macro redefinition error is to not define it: https://github.com/zig-gamedev/zig-gamedev/pull/616/commits/2f699d72e2b742efe6fb49cb1d6e1e843a8e77e1
