### ISSUE TITLE
Update to latest jolt physics

### ISSUE THREAD

**Issue by Pyrolistical** [zig-gamedev/zig-gamedev#622]
Jolt physics was last updated at version 3.0.1. Latest release is 5.0.0

[Release notes](https://jrouwe.github.io/JoltPhysics/md__docs_2_release_notes.html)

Breaking changes:
[Changes between v3.0.1 and v4.0.0](https://jrouwe.github.io/JoltPhysics/md__docs_2_a_p_i_changes.html#autotoc_md31)
[Changes between v4.0.0 and v5.0.0](https://jrouwe.github.io/JoltPhysics/md__docs_2_a_p_i_changes.html#autotoc_md25)

**Comment by Pyrolistical** [comment]
I tried to update to 5.0.0 and it fails to compile since JoltC needs to be resynced.

### Sample of JoltC issues
1. [`BodyManager.mNumActiveBodies` and `BodyManager.mActiveBodies` becames an array](https://github.com/jrouwe/JoltPhysics/pull/644/files#diff-9934629525caac92050493731fe814b7a7433dfaee6dc82f3676314b4b90d7cdL304-L307)
2. `JPC_BodyCreationSettings` out of sync
3. `JPC_ContactSettings` out of sync
4. `JPC_SHAPE_TYPE_USER[1-4]` out of sync
5. `JPC_SHAPE_SUB_TYPE_USER[1-8]` out of sync
6. `JPC_SHAPE_SUB_TYPE_USER_CONVEX1[1-2]` out of sync

**Comment by pfeodrippe** [comment]
@Pyrolistical @hazeycode, I am working on a Clojure game framework and I’m using zphysics, it’s pretty awesome, thanks for this work!!

If you want some reference, I have been able to use the latest version of Jolt (as of today), see the changes at https://github.com/zig-gamedev/zig-gamedev/commit/9ab61bd6f54e1967f140205df5cfe27d4ca02aee (I have deleted the src zig file as there were expected size differences for some structs and I am not using it).

**Comment by Pyrolistical** [comment]
taking a look at this now @pfeodrippe

**Comment by a-day-old-bagel** [comment]
I can give this a shot, if nobody else is actively working on it.

Latest release is now 5.1.0, it appears.

**Comment by a-day-old-bagel** [comment]
Ok, I got the new version compiling, but I'm still tracking down a few memory-related crashes and test fails, probably due to some structure I missed and still need to update to reflect Jolt's changes.

But basically, this looks quite doable and near completion.

**Comment by a-day-old-bagel** [comment]
Ok, [PR open now for *careful* review](https://github.com/zig-gamedev/zig-gamedev/pull/723) (I'm not super confident I was able to catch all the necessary changes)

**Comment by hazeycode** [comment]
Closed by https://github.com/zig-gamedev/zig-gamedev/pull/723
