### ISSUE TITLE
Update zflecs to flecs 4

### ISSUE THREAD

**Issue by giusdp** [zig-gamedev/zig-gamedev#649]
Hey folks.

Flecs had very recently a new major version, perhaps this issue can be used to keep track for the update of the relative zflecs.
If possible I could try my hand at the update, although I'm pretty new to zig and I might need some guidance.

I think the major change is the removal of `filter`, as it was merged with `query`. I saw zflecs already has several tests in place, so there is a way to check if things are still working after the migration to flecs 4.

**Comment by hazeycode** [comment]
Completed by https://github.com/zig-gamedev/zig-gamedev/pull/673
