### ISSUE TITLE
zmesh: zcgltf is hidden

### ISSUE THREAD

**Issue by Jack-Ji** [zig-gamedev/zig-gamedev#690]
Looks like recent refactoring job has made zcgltf private, which make accessing gltf's internal structure impossible. If I'm not mistaken, it is necessary to consider zcgltf.Node's parent-children relationship in order to correctly render gltf model, not to mention skin animation.

**Comment by hazeycode** [comment]
Sorry about the breakage. Thanks for letting me know. I have employed `pub usingnamespace` as a temporary workaround.
