### ISSUE TITLE
minimal_sdl_gl: prebuilt SDL2 is not installed when running specific build command

### ISSUE THREAD

**Issue by gegogi** [zig-gamedev/zig-gamedev#696]
When you run `zig build minimal_sgl_gl` right after cloning the repo, it will succeed to compile and copy the exe file to `zig-out/bin` dir.
But the related dependency binaries are not. They can be installed only by the top-level `zig build` command.
I had looked into it a bit and noticed the install step of dependent arfiacts depend on the install step of main build object like this:
```zig
    if (@import("zsdl").install_SDL2(b, options.target.result, sdl2_libs_path, .bin)) |install_sdl2_step| {
        b.getInstallStep().dependOn(install_sdl2_step);
    }
``` 
Shouldn't it depend on each project specific install step?

**Comment by hazeycode** [comment]
Thanks for the report. I have pushed a minimal fix for this but I will also be following up with revisions to the build system.

**Comment by hazeycode** [comment]
Also see https://github.com/zig-gamedev/zig-gamedev/pull/708
