### ISSUE TITLE
zsdl: Duplicated dependencies in user code.

### ISSUE THREAD

**Issue by XReaper95** [zig-gamedev/zig-gamedev#712]
Hello, first of all I would like to thank everyone for the hard work on this amazing project! So I was setting up a project that uses `zsdl`, and noticed that the prebuilt SDL dependencies are already specified at `libs\zsdl\build.zig.zon`. In the README it says that you should also add these dependencies in your own `build.zig.zon` file:

> also add the following if you want to use our prebuilt libraries instead of system installed dependencies
>```zig
>        .@"sdl2-prebuilt-macos" = .{
>           .url = "https://github.com/zig-gamedev/sdl2-prebuilt-macos/archive/f14773fa3de719b3a399b854c31eb4139d63842f.tar.gz",
>           .hash = "12205cb2da6fb4a7fcf28b9cd27b60aaf12f4d4a55be0260b1ae36eaf93ca5a99f03",
>           .lazy = true,
>        },
>         ...........
>```

By ignoring this the project wont compile. I fixed it on my local copy, but it requires to change the public API on the `libs\zsdl\build.zig` script. Is there a reason for this? I personally would prefer to keep everything in a single place.

**Comment by hazeycode** [comment]
Sorry this was a mistake and has been fixed here: https://github.com/zig-gamedev/zig-gamedev/commit/b570c0e4699f0f2a9acf395a6461ad7014385e4f
