### ISSUE TITLE
ztracy Always Enabled

### ISSUE THREAD

**Issue by jcalabro** [zig-gamedev/zig-gamedev#714]
Hey there! Even when [enable_ztracy](https://github.com/zig-gamedev/zig-gamedev/blob/d96ecc993bcfc4461f44d9432589dc9273952a78/libs/ztracy/build.zig#L8C10-L12) is false, tracy is enabled and the application is listening on port 8080.

Take the procedural mesh sample application for instance:

![image](https://github.com/user-attachments/assets/90a2433a-2aa0-4cf7-b743-66fea75fec36)

You can see that the application is listening on 8086 and tracy can find it without issue even though `enable_ztracy` is false.

I think we want to change [this line](https://github.com/zig-gamedev/zig-gamedev/blob/d96ecc993bcfc4461f44d9432589dc9273952a78/libs/ztracy/build.zig#L50) to:

```zig
if (options.enable_ztracy) "-DTRACY_ENABLE" else "",
```

Which appears to solve the issue locally. Let me know what you think!
\- Jim

**Comment by hazeycode** [comment]
Fixed by https://github.com/zig-gamedev/zig-gamedev/pull/722

**Comment by jcalabro** [comment]
Thanks all! :heart:
